#!/usr/bin/env bash

hc() {
  herbstclient "$@"
}

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Return spawn ${TERMINAL:-hyper} # use your $TERMINAL with xfce4-terminal as fallback

hc set default_frame_layout 1

# basic movement
# focusing clients
#hc keybind $Mod-Left  focus left
#hc keybind $Mod-Down  focus down
#hc keybind $Mod-Up    focus up
#hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
#hc keybind $Mod-Control-Left    resize left +$resizestep
#hc keybind $Mod-Control-Down    resize down +$resizestep
#hc keybind $Mod-Control-Up      resize up +$resizestep
#hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( {1..6} )
tag_keys=( {1..6} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
  hc add "${tag_names[$i]}"
  key="${tag_keys[$i]}"
  if ! [ -z "$key" ] ; then
    hc keybind "$Mod-$key" use_index "$i"
    hc keybind "$Mod-Shift-$key" move_index "$i"
  fi
done

hc keybind $Mod-"1" use "1"

# cycle through tags
hc keybind $Mod-Right use_index +1 --skip-visible
hc keybind $Mod-Left  use_index -1 --skip-visible
hc keybind $Mod-Control-Right move_index +1 --skip-visible
hc keybind $Mod-Control-Left  move_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-w close
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space \
  or , and . compare tags.focus.curframe_wcount = 2 \
  . cycle_layout +1 vertical horizontal max vertical grid \
  , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# system
hc keybind XF86MonBrightnessUp   spawn xbacklight +5
hc keybind XF86MonBrightnessDown spawn xbacklight -5

hc keybind XF86AudioRaiseVolume  spawn amixer -q set Master 5%+ unmute
hc keybind XF86AudioLowerVolume  spawn amixer -q set Master 5%- unmute
hc keybind XF86AudioMute         spawn amixer -q set Master toggle

hc keybind XF86AudioPlay         spawn /home/etienne/.scripts/spotify.sh 0
hc keybind XF86AudioNext         spawn /home/etienne/.scripts/spotify.sh 1
hc keybind XF86AudioPrev         spawn /home/etienne/.scripts/spotify.sh 2

hc keybind $Mod-space spawn ~/.rofi
hc keybind $Mod-o spawn /home/etienne/.scripts/lock
hc keybind $Mod-p spawn /home/etienne/.scripts/suspend

hc keybind $Mod-g toggle window_gap

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#666666'
hc set frame_border_normal_color '#444444'
hc set frame_bg_normal_color '#444444'
hc set frame_bg_active_color '#444444'
hc set frame_border_width 0
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 2
hc set frame_gap 0

hc attr theme.active.color '#666666'
hc attr theme.normal.color '#444444'
hc attr theme.urgent.color orange
hc attr theme.inner_width 0
hc attr theme.inner_color "#444444"
hc attr theme.border_width 0
hc attr theme.floating.border_width 1
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color "#444444"
hc attr theme.active.inner_color '#444444'
hc attr theme.active.outer_color '#444444'
hc attr theme.background_color '#444444'

hc set window_gap 20
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

# rules
hc unrule -F
hc rule focus=off # normally focus new clients
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# application rules
hc rule class=Google-chrome tag=1
hc rule class=Spotify tag=6
hc rule class=Atom tag=3
hc rule class=Firefox tag=1

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

herbstclient pad 0 25 0 0


xrdb -merge ~/.Xressources &

nitrogen --restore &
compton &

/opt/google/chrome/google-chrome --no-startup-window &

$HOME/.config/polybar/launch.sh
